# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a8670af227ce72c7ebcfedfa5cbfbf995f758e92688d3aeae9de54a49b97760ccbef8ec80a0bcf36d3fcc096afa9e08d196623cdf8d74d501c57622196f97f

test:
  secret_key_base: 4983651913c1751e6cb3cb9fa7fd17984e7a16998db4e3d99d9c8f1e6181f4315dffc45df4f9dbc422fcced0d53f18e45edc9850325c063467e933b549f53083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
